### ISSUE TITLE
Text is written on the video play

### ISSUE THREAD

**Issue by pkcnetsolutionsindia** [wuqiong/VLCKit-SDK#1]
I integrate the vlc framework. When I play video then on the top right side, some text(diveinedu etc) are shown. How to remove that text overlay.

**Comment by wuqiong** [comment]
@pkcnetsolutionsindia  
Sorry, at the beginning time, this framework was builded for  my students' demo projects.  about a month ago,  I have already updated the MobileVLCKit framework for iOS use which can turn off the OSD watermark.  I will turn to update this VLCKit framework for Mac OS X use in some days, you know, the Spring Festival is coming. ;-)

**Comment by pkcnetsolutionsindia** [comment]
@wuqiong Thank you for the quick response. I will wait for your update. Enjoy your festival.

Best regards,
Pardeep

**Comment by wuqiong** [comment]
@pkcnetsolutionsindia   Please pull your local repo, I have updated the VLCKit framework, and remove that OSD Text.  Enjoy your project.
Best regards,
吴琼

**Comment by pkcnetsolutionsindia** [comment]
Thank you. It works like a charm.

Regards,
Pardeep
